name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build
      run: go build -v wrapped-executable

    - name: Package
      run: |
        mkdir build
        mv wrapped-executable build/
        cp win_service_wrapper/win_sw.xml build/pc2mqtt.xml
        cp win_service_wrapper/win_sw.exe build/pc2mqtt.exe
        mv build/ pc2mqtt/
        zip pc2mqtt-linux.zip pc2mqtt/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pc2mqtt-linux
        path: pc2mqtt-linux.zip 
