name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build
      run: go build -v -o pc2mqtt

    - name: Package
      run: |
        tar xvzf pc2mqtt-linux.tar.gz pc2mqtt

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pc2mqtt-linux
        path: pc2mqtt-linux.tar.gz
